name: Populate Services

on:
  schedule:
    - cron: "0 2 * * *"
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  populate-services:
    uses: unitysvc-labs/.github/.github/workflows/seller-populate-services.yml@main
    secrets: inherit
