name: Upload Data to Production

on:
  workflow_dispatch:

jobs:
  upload:
    uses: unitysvc-labs/.github/.github/workflows/seller-upload-production.yml@main
    secrets: inherit
    permissions:
      contents: write
